version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hf_backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app/app # For live reload during development
    env_file:
      - .env # Loads variables from .env file (if it exists)
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hf_frontend_service
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
