version: '3.8'

services:
  app: # Renamed from 'backend' to 'app' as it now serves both
    build:
      context: .
      dockerfile: Dockerfile # This is the backend Dockerfile that now includes frontend assets
    container_name: hf_combined_app_service
    ports:
      # Map host port 8080 (for browser access) to container port 8000 (where FastAPI serves everything)
      - "8080:8000"
    volumes:
      # Mount backend app code for live reload during development.
      - ./hf_model_explorer_service/hf_model_explorer_service:/usr/src/app/app
    env_file:
      - .env # Loads variables from .env file in the project root (if it exists)
    # networks:
    #   - app_network # Optional for single service, can be kept for future expansion

# networks: # Optional for single service
#   app_network:
#     driver: bridge
